import type { GeneratedFile } from "./studio";
import { slugify } from "./studio";

type PullRequestResult = {
  branch: string;
  pullRequestUrl: string;
  files: string[];
};

function requiredEnv(name: string) {
  const value = process.env[name];

  if (!value) {
    throw new Error(`${name} is not configured.`);
  }

  return value;
}

async function githubFetch<T>(path: string, init: RequestInit = {}) {
  const token = requiredEnv("GITHUB_TOKEN");
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...init.headers
    }
  });

  const data = (await response.json().catch(() => null)) as T | { message?: string } | null;

  if (!response.ok) {
    throw new Error(
      typeof data === "object" && data && "message" in data && data.message
        ? data.message
        : `GitHub API request failed: ${response.status}`
    );
  }

  return data as T;
}

function repo() {
  return requiredEnv("GITHUB_REPOSITORY");
}

export async function createContentPullRequest(params: {
  title: string;
  summary: string;
  files: GeneratedFile[];
  branchPrefix: string;
}) {
  const repository = repo();
  const baseBranch = process.env.GITHUB_BASE_BRANCH ?? "main";
  const branch = `${params.branchPrefix}/${slugify(params.title)}-${Date.now()}`;

  const baseRef = await githubFetch<{ object: { sha: string } }>(
    `/repos/${repository}/git/ref/heads/${baseBranch}`
  );

  await githubFetch(`/repos/${repository}/git/refs`, {
    method: "POST",
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: baseRef.object.sha
    })
  });

  for (const file of params.files) {
    await githubFetch(`/repos/${repository}/contents/${file.path}`, {
      method: "PUT",
      body: JSON.stringify({
        message: params.title,
        content:
          file.encoding === "base64"
            ? file.content
            : Buffer.from(file.content, "utf8").toString("base64"),
        branch
      })
    });
  }

  const pullRequest = await githubFetch<{ html_url: string }>(`/repos/${repository}/pulls`, {
    method: "POST",
    body: JSON.stringify({
      title: params.title,
      head: branch,
      base: baseBranch,
      body: `${params.summary}\n\nGenerated by the CareerOps studio server API.`
    })
  });

  return {
    branch,
    pullRequestUrl: pullRequest.html_url,
    files: params.files.map((file) => file.path)
  } satisfies PullRequestResult;
}
