import type { GeneratedFile } from "./studio";
import { slugify } from "./studio";

type PullRequestResult = {
  branch: string;
  pullRequestUrl: string;
  files: string[];
};

function requiredEnv(name: string) {
  const value = process.env[name]?.trim();

  if (!value) {
    throw new Error(`${name} is not configured.`);
  }

  return value;
}

function githubHeaders(initHeaders?: HeadersInit) {
  const token = requiredEnv("GITHUB_TOKEN");

  return {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
    ...initHeaders
  };
}

async function githubFetch<T>(path: string, init: RequestInit = {}) {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: githubHeaders(init.headers)
  });

  const data = (await response.json().catch(() => null)) as T | { message?: string } | null;

  if (!response.ok) {
    throw new Error(
      typeof data === "object" && data && "message" in data && data.message
        ? data.message
        : `GitHub API request failed: ${response.status}`
    );
  }

  return data as T;
}

function repo() {
  const repository = requiredEnv("GITHUB_REPOSITORY");

  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) {
    throw new Error("GITHUB_REPOSITORY must use owner/repo format, for example Kittipong-Dev/Portfolio.");
  }

  if (repository.split("/").some((part) => part.endsWith("."))) {
    throw new Error("GITHUB_REPOSITORY must not include trailing dots.");
  }

  return repository;
}

function encodeGitHubPath(path: string) {
  return path.split("/").map(encodeURIComponent).join("/");
}

function normalizeBase64(value: string) {
  return value.replace(/\s+/g, "");
}

function fileContentBase64(file: GeneratedFile) {
  return file.encoding === "base64"
    ? normalizeBase64(file.content)
    : Buffer.from(file.content, "utf8").toString("base64");
}

async function existingContent(repository: string, filePath: string, branch: string) {
  const response = await fetch(
    `https://api.github.com/repos/${repository}/contents/${encodeGitHubPath(filePath)}?ref=${encodeURIComponent(branch)}`,
    {
      headers: githubHeaders()
    }
  );

  if (response.status === 404) {
    return undefined;
  }

  const data = (await response.json().catch(() => null)) as
    | { content?: string; message?: string; sha?: string; type?: string }
    | null;

  if (!response.ok) {
    throw new Error(data?.message ?? `GitHub content lookup failed: ${response.status}`);
  }

  if (data?.type !== "file") {
    throw new Error(`${filePath} exists on GitHub but is not a file.`);
  }

  return {
    content: normalizeBase64(data?.content ?? ""),
    sha: data?.sha
  };
}

export async function createContentPullRequest(params: {
  title: string;
  summary: string;
  files: GeneratedFile[];
  branchPrefix: string;
}) {
  const repository = repo();
  const baseBranch = process.env.GITHUB_BASE_BRANCH?.trim() || "main";
  const branch = `${params.branchPrefix}/${slugify(params.title)}-${Date.now()}`;

  const baseRef = await githubFetch<{ object: { sha: string } }>(
    `/repos/${repository}/git/ref/heads/${baseBranch}`
  );
  const baseSha = baseRef.object?.sha;

  if (!baseSha) {
    throw new Error(`Could not resolve SHA for base branch "${baseBranch}". Check GITHUB_BASE_BRANCH and repository access.`);
  }

  await githubFetch(`/repos/${repository}/git/refs`, {
    method: "POST",
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: baseSha
    })
  });

  const changedFiles: GeneratedFile[] = [];

  for (const file of params.files) {
    const current = await existingContent(repository, file.path, branch);
    const content = fileContentBase64(file);

    if (current?.content === content) {
      continue;
    }

    await githubFetch(`/repos/${repository}/contents/${file.path}`, {
      method: "PUT",
      body: JSON.stringify({
        message: params.title,
        content,
        branch,
        ...(current?.sha ? { sha: current.sha } : {})
      })
    });
    changedFiles.push(file);
  }

  if (changedFiles.length === 0) {
    throw new Error("No file changes detected. Update at least one field or upload a new file before creating a pull request.");
  }

  const pullRequest = await githubFetch<{ html_url: string }>(`/repos/${repository}/pulls`, {
    method: "POST",
    body: JSON.stringify({
      title: params.title,
      head: branch,
      base: baseBranch,
      body: `${params.summary}\n\nGenerated by the CareerOps studio server API.`
    })
  });

  return {
    branch,
    pullRequestUrl: pullRequest.html_url,
    files: changedFiles.map((file) => file.path)
  } satisfies PullRequestResult;
}
